### ISSUE TITLE
请问大概需要多长时间训练完成

### ISSUE THREAD

**Issue by yuyukuy534** [zZhiG/crackmer#1]
您好。请问大概需要多长时间能够训练完成？

**Comment by zZhiG** [comment]
你可以试着在训练过程中，打印损失值或者其他信息，来验证程序是否正常运行。
我们上传的训练代码中，会计算结果的各项指标，这个过程是缓慢的。
如果你不需要得知中间结果，可以删除这一步骤，这样可以减少训练时间。

**Comment by yuyukuy534** [comment]
> 你可以试着在训练过程中，打印损失值或者其他信息，来验证程序是否正常运行。 我们上传的训练代码中，会计算结果的各项指标，这个过程是缓慢的。 如果你不需要得知中间结果，可以删除这一步骤，这样可以减少训练时间。

好的，非常感谢您的回复

**Comment by zZhiG** [comment]
CrackForest: https://github.com/cuilimeng/CrackForest-dataset/tree/master
CrackTree 260: https://github.com/qinnzou/DeepCrack

**Comment by yuyukuy534** [comment]
> CrackForest: https://github.com/cuilimeng/CrackForest-dataset/tree/master CrackTree 260: https://github.com/qinnzou/DeepCrack

收到，非常感谢

**Comment by yuyukuy534** [comment]
> CrackForest: https://github.com/cuilimeng/CrackForest-dataset/tree/master CrackTree 260: https://github.com/qinnzou/DeepCrack

收到，非常感谢

**Comment by cyberblue1** [comment]
你训练了吗，用了多长时间
