### ISSUE TITLE
数据集预处理问题

### ISSUE THREAD

**Issue by shuangzhen361** [zZhiG/crackmer#3]
作者您好，感谢您优秀论文做出的贡献。文章中提到首先将数据集图像的大小调整为1.25倍，然后随机地将其水平和垂直翻转，随机旋转16度，最后将其集中裁剪到所需的大小。想问下您最后将其集中裁剪到的大小是多少了？还是裁剪到原始数据集的大小吗？

**Comment by zZhiG** [comment]
我们将图片全部裁剪为512*512大小

**Comment by yuyukuy534** [comment]
好的，谢谢

**Comment by shuangzhen361** [comment]
好的，谢谢
