### ISSUE TITLE
数据增强问题

### ISSUE THREAD

**Issue by fhsufve** [zZhiG/crackmer#6]
作者您好，感谢您优秀的论文。请问可以发一下您对数据集进行数据增强的代码吗，我自己写的数据增强代码跑出来的效果很差，想看下您数据增强的代码。非常感谢您，期待您的回复！

**Comment by zZhiG** [comment]
我们上传了相应的代码：
https://github.com/zZhiG/SER/blob/main/util/loader.py
https://github.com/zZhiG/crackmer/blob/main/utils/dataloader.py
在训练过程中，会随机对数据进行相应的处理，希望可以对你有所帮助

**Comment by yuyukuy534** [comment]
> 我们上传了相应的代码： https://github.com/zZhiG/SER/blob/main/util/loader.py https://github.com/zZhiG/crackmer/blob/main/utils/dataloader.py 在训练过程中，会随机对数据进行相应的处理，希望可以对你有所帮助

非常感谢您的指导
