### ISSUE TITLE
计算mIoU值

### ISSUE THREAD

**Issue by yuyukuy534** [zZhiG/crackmer#7]
作者您好，我在使用您论文中的计算方式测试mIoU指标值时(计算方式如下图所示)，测试结果只有60%多，请问可以发一下您计算mIoU指标的代码吗，我想参考下。非常感谢您，期待您的回复！
<img width="355" alt="22e552c3811799f9a8f6d6081e5ea18" src="https://github.com/user-attachments/assets/b4417dc5-67e1-4514-a6cf-1471952232b5">

**Comment by zZhiG** [comment]
你好，之前我们计算mIoU会考虑背景类进行，你的代码看上去只计算了裂缝这一个类别。在后续我们也是只计算了裂缝类：
https://github.com/zZhiG/DECS-Net/blob/main/statistic.py

这是我们之前的计算方式：
![image](https://github.com/user-attachments/assets/0cd1a4fe-f04c-45da-be5d-53c3c2298465)

**Comment by yuyukuy534** [comment]
收到，感谢您的指导
